#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: The Randolph Glacier Inventory version 7
author: RGI Consortium  # The author of the book
copyright: "2022"  # Copyright year to be placed in the footer
logo: img/logo.png  # A path to the book logo

repository:
  url: https://github.com/GLIMS-RGI/rgi_user_guide
  path_to_book: docs 
  branch: main
bibtex_bibfiles:
   - references_cleaned.bib
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  google_analytics_id: 
  extra_footer: |
    <p>
    <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">
      <img align="right" class="margin" src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by.svg" width="88px">
    </a>
    This work is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">Creative Commons Attribution 4.0 International (CC BY 4.0) license</a> unless specified otherwise.
    <br>
    &copy; Copyright RGI Consortium 2022-2023.
    </p>
sphinx:
  config:
    html_show_copyright: false
    bibtex_reference_style: author_year
execute:
  execute_notebooks: auto
  allow_errors: true
exclude_patterns: [.virtual_documents/*]
parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
    